version: '3.9'

services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: masa561
      POSTGRES_PASSWORD: masaharu0530
      POSTGRES_DB: coginner_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: masa561
      DATABASE_PASSWORD: masaharu0530
      RAILS_ENV: development

volumes:
  db_data:
