version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: masa561
      POSTGRES_PASSWORD: masa0530
      POSTGRES_DB: coginner_development
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: masa561
      POSTGRES_PASSWORD: masa0530
      POSTGRES_DB: coginner_development
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      RAILS_ENV: development
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle
    stdin_open: true
    tty: true

volumes:
  db_data:
  bundle_data:
