# syntax=docker/dockerfile:1

FROM ruby:3.3.6-slim

WORKDIR /rails

# Rails の環境を development にする
ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle

# 必要なパッケージをインストール
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    curl \
    git \
    libpq-dev \
    libvips \
    nodejs \
    npm \
    postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# Gemfile & Gemfile.lock をコピーして bundle install
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリケーションコードをコピー
COPY . .

# bin/dev を叩けるようにして、改行コード問題を回避
RUN chmod +x bin/* && sed -i "s/\r$//g" bin/*

EXPOSE 3000

# 開発用は bin/dev をデフォルトで起動
CMD ["bin/dev"]
