# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "masa561" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "masa0530" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "coginner_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB") { "coginner_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_PROD_DB") { "coginner_production" } %>
